# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Cambiado de macOS-latest a windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Check Hands_on_I.Rmd
        run: if (Test-Path Hands_on_I.Rmd) { exit 0 } else { Write-Host "Missing Hands_on_I.Rmd"; exit 1 }

      - name: Install R and Bioconductor packages
        run: Rscript -e '
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager");
          BiocManager::install(c("ComplexHeatmap", "circlize"));
          install.packages(c("here", "readxl", "tidyverse", "corrplot", "mlbench", "GGally", "dplyr", "tidyr", "ggplot2", "gtable", "data.table", "gridExtra", "grid", "patchwork", "stringr", "rmarkdown", "janitor"), repos="http://cran.rstudio.com")'

      - name: Render Hands_on_I.html
        run: Rscript -e 'rmarkdown::render("Hands_on_I.Rmd")'

      - name: Check Hands_on_I.html
        run: if (Test-Path Hands_on_I.html) { exit 0 } else { Write-Host "Missing Hands_on_I.html"; exit 1 }

